### ISSUE TITLE
E-Paper

### ISSUE THREAD

**Issue by koopermark** [JohnMasen/SmartClock#1]
Hi, 

Did you manage to got this project to work.
I am looking at creating an alarm clock with a waveshare 1.54inch e-paper screen but I don't know where to start, I have only some experiencing with VB.net and WPF but looking to go over to IOT.

I am looking for pointers and the only project similar to what i was looking for is yours.

I would really appreciate you helping if you can.
Sorry for posting this as an issue, I did download you project but I couldn't get it to work

thanks

**Comment by JohnMasen** [comment]
hi,
this project is designed to run on Windows IOT core (Raspberry 3B), unfortunately the code is NOT working anymore. however, the only problem is the core engine ChakraCore.NET has been rewritten. I'm going to restart this project about 1 month later(hope I can finish my current stuff by then).
for this project, there's 3 key parts:
1. dynamic drawing script: a javascript based drawing enging, translate high level API to low level drawing API, kind like pixel shader in DirectX.
2. E-Eink driver: translate low level drawing API to serial command
3. Host Shell: hosts both of above and provide basic Clock logic.

this project is also designed to support plug-in with internet access, you can use this to implement weather forcast, reminder, Cortana... in your own clock.
For start your IoT journey, I suggest you read the GPIO part of windows IOT. controlling low level device is real fun :)
Feel free to open more issue if you need help, hope this can help you.

**Comment by koopermark** [comment]
Hi, 

Many thanks for getting back to me, I will have a look at the GPIO part or windows IOT.

At first glance this seems to be way above my head but hopefully something may fall into place.

Thanks again.
